const quizzes = [
  {
    travel: [
      {
        questionTitle: 'Which of the following is the nickname of Japan?',
        answer1: 'land of thousand lakes',
        answer2: 'land of golden pagoda',
        answer3: 'land of the rising sun',
        answer4: 'none of the above',
        correctAnswer: 'answer3',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 28,
      },
      {
        questionTitle: 'What is the most populous country in Africa?',
        answer1: 'nigeria',
        answer2: 'chad',
        answer3: 'cameroon',
        answer4: 'morocco',
        correctAnswer: 'answer1',
        questionTime: 15,
        questionType: 'quiz',
        questionPoints: 200,
        questionId: 18,
      },
      {
        questionTitle: 'Approximately 60 per cent of the world’s lakes can be found in Canada.',
        answer1: 'False',
        answer2: 'True',
        correctAnswer: 'answer2',
        questionTime: 10,
        questionType: 'trueorfalse',
        questionPoints: 100,
        questionId: 48,
      },

      {
        questionTitle: 'What is the most southerly capital city in the world?',
        answer1: 'Cape Town, South Africa',
        answer2: 'Buenos Aires, Argentina',
        answer3: 'Wellington, New Zealand',
        answer4: 'Canberra, Australia',
        correctAnswer: 'answer3',
        questionTime: 10,
        questionType: 'quiz',
        questionPoints: 200,
        questionId: 18,
      },

      {
        questionTitle: 'Which country in the world is comprised of up to 180,000 islands?',
        answer1: 'Malaysia',
        answer2: 'Finland',
        answer3: 'Norway',
        answer4: 'Japan',
        correctAnswer: 'answer2',
        questionTime: 15,
        questionType: 'quiz',
        questionPoints: 100,
        questionId: 58,
      },

      {
        questionTitle: 'What is the largest harbour in Europe?',
        answer1: 'Rotterdam, the Netherlands',
        answer2: 'Hamburg, Germany',
        answer3: 'Antwerp, Belgium',
        answer4: 'Bremerhaven, Germany',
        correctAnswer: 'answer1',
        questionTime: 20,
        questionType: 'quiz',
        questionPoints: 200,
        questionId: 40,
      },

      {
        questionTitle: 'Volga river flows through Moscow, the capital of Russia?',
        answer1: 'True',
        answer2: 'False',
        correctAnswer: 'answer1',
        questionTime: 10,
        questionType: 'trueorfalse',
        questionPoints: 100,
        questionId: 80,
      },

      {
        questionTitle: 'What is the currency of Hungary?',
        answer1: 'Hungarian euro',
        answer2: 'Hungarian dollar',
        answer3: 'Hungarian rupee',
        answer4: 'Hungarian forint',
        correctAnswer: 'answer4',
        questionTime: 30,
        questionType: 'quiz',
        questionPoints: 200,
        questionId: 10,
      },
    ],
  },
  {
    random: [
      {
        questionTitle: 'What is the only food that cannot go bad?',
        answer1: 'Dark chocolate',
        answer2: 'Peanut butter',
        answer3: 'Canned tuna',
        answer4: 'Honey',
        correctAnswer: 'answer4',
        questionTime: 10,
        questionType: 'quiz',
        questionPoints: 100,
        questionId: 28,
      },

      {
        questionTitle: 'What sport has been played on the moon?',
        answer1: 'Frisbee',
        answer2: 'Soccer',
        answer3: 'Golf',
        answer4: 'Bocce ball',
        correctAnswer: 'answer3',
        questionType: 'quiz',
        questionTime: 30,
        questionPoints: 200,
        questionId: 43,
      },

      {
        questionTitle: 'Which country’s national animal is a unicorn?',
        answer1: 'Denmark',
        answer2: 'Scotland',
        answer3: 'France',
        answer4: 'New Zealand',
        correctAnswer: 'answer2',
        questionTime: 20,
        questionType: 'quiz',
        questionPoints: 100,
        questionId: 45,
      },

      {
        questionTitle: 'Dr. Pepper is the oldest soft drink in the United States?',
        answer1: 'True',
        answer2: 'False',
        correctAnswer: 'answer1',
        questionTime: 20,
        questionType: 'trueorfalse',
        questionPoints: 100,
        questionId: 44,
      },

      {
        questionTitle: 'What element does the chemical symbol Au stand for?',
        answer1: 'Silver',
        answer2: 'Magnesium',
        answer3: 'Salt',
        answer4: 'Gold',
        correctAnswer: 'answer4',
        questionTime: 15,
        questionType: 'quiz',
        questionPoints: 200,
        questionId: 32,
      },

      {
        questionTitle: 'Which of these EU countries does not use the euro as its currency?',
        answer1: 'Poland',
        answer2: 'Denmark',
        answer3: 'Sweden',
        answer4: 'All of the above',
        correctAnswer: 'answer4',
        questionTime: 30,
        questionType: 'quiz',
        questionPoints: 100,
        questionId: 55,
      },

      {
        questionTitle: 'Octopus has three hearts?',
        answer1: 'False',
        answer2: 'True',
        correctAnswer: 'answer2',
        questionTime: 10,
        questionType: 'trueorfalse',
        questionPoints: 200,
        questionId: 57,
      },

      {
        questionTitle: 'What’s the name of Hagrid’s pet spider?',
        answer1: 'Crookshanks',
        answer2: 'Nigini',
        answer3: 'Aragog',
        answer4: 'Mosag',
        correctAnswer: 'answer3',
        questionTime: 15,
        questionType: 'quiz',
        questionPoints: 100,
        questionId: 60,
      },

      {
        questionTitle: 'What animal is the closest living relative of a human?',
        answer1: 'Gorillas',
        answer2: 'Monkeys',
        answer3: 'Homo sapiens',
        answer4: 'Bonobos',
        correctAnswer: 'answer4',
        questionTime: 15,
        questionType: 'quiz',
        questionPoints: 100,
        questionId: 60,
      },

      {
        questionTitle: 'How many islands are in Hawaii?',
        answer1: '137',
        answer2: '7',
        answer3: '11',
        answer4: '48',
        correctAnswer: 'answer1',
        questionTime: 15,
        questionType: 'quiz',
        questionPoints: 100,
        questionId: 60,
      },
    ],
  },
  {
    Mathematics: [
      {
        questionTitle: 'What is the value of pi?',
        answer1: '3.14',
        answer2: '2.17',
        answer3: '1.62',
        answer4: '4.99',
        correctAnswer: 'answer1',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 1,
      },
      {
        questionTitle: 'What is the formula for calculating the area of a circle?',
        answer1: 'pi * diameter',
        answer2: 'pi * radius^2',
        answer3: 'pi * circumference',
        answer4: 'diameter * radius',
        correctAnswer: 'answer2',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 2,
      },
      {
        questionTitle: 'What is the formula for calculating the volume of a sphere?',
        answer1: '4/3 * pi * radius^3',
        answer2: '2 * pi * radius^2',
        answer3: 'pi * diameter',
        answer4: 'pi * radius^2',
        correctAnswer: 'answer1',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 3,
      },
      {
        questionTitle: 'What is the Pythagorean theorem?',
        answer1: 'a^2 + b^2 = c^2',
        answer2: 'a^2 - b^2 = c^2',
        answer3: 'a^2 + b^2 + c^2',
        answer4: 'a^3 + b^3 = c^3',
        correctAnswer: 'answer1',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 4,
      },
      {
        questionTitle: 'What is the formula for calculating the slope of a line?',
        answer1: 'rise / run',
        answer2: 'run / rise',
        answer3: 'rise * run',
        answer4: 'rise - run',
        correctAnswer: 'answer1',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 5,
      },
    ],
  },
  {
    'Marvel Cinematic Universe': [
      {
        questionTitle: 'Who is the leader of the Avengers?',
        answer1: 'Iron Man',
        answer2: 'Captain America',
        answer3: 'Hulk',
        answer4: 'Thor',
        correctAnswer: 'answer2',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 1,
      },
      {
        questionTitle: "What is the name of Tony Stark's AI assistant?",
        answer1: 'JARVIS',
        answer2: 'FRIDAY',
        answer3: 'EDITH',
        answer4: 'Ultron',
        correctAnswer: 'answer1',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 2,
      },
      {
        questionTitle: "What is the name of the villain in the movie 'Black Panther'?",
        answer1: 'Killmonger',
        answer2: 'Thanos',
        answer3: 'Loki',
        answer4: 'Red Skull',
        correctAnswer: 'answer1',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 3,
      },
      {
        questionTitle: "What is the name of the metal used to create Captain America's shield?",
        answer1: 'Vibranium',
        answer2: 'Adamantium',
        answer3: 'Uru',
        answer4: 'Mithril',
        correctAnswer: 'answer1',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 4,
      },
      {
        questionTitle: "What is the name of the villain in the movie 'Spider-Man: Homecoming'?",
        answer1: 'The Vulture',
        answer2: 'The Green Goblin',
        answer3: 'Doctor Octopus',
        answer4: 'Sandman',
        correctAnswer: 'answer1',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 5,
      },
    ],
  },
  {
    'Harry Potter': [
      {
        questionTitle: "What is the name of Harry Potter's owl?",
        answer1: 'Hedwig',
        answer2: 'Scabbers',
        answer3: 'Crookshanks',
        answer4: 'Fawkes',
        correctAnswer: 'answer1',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 6,
      },
      {
        questionTitle: 'What is the name of the school that Harry Potter attends?',
        answer1: 'Hogwarts',
        answer2: 'Beauxbatons',
        answer3: 'Durmstrang',
        answer4: 'Ilvermorny',
        correctAnswer: 'answer1',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 7,
      },
      {
        questionTitle: 'What is the name of the main villain in the Harry Potter series?',
        answer1: 'Voldemort',
        answer2: 'Bellatrix Lestrange',
        answer3: 'Severus Snape',
        answer4: 'Lucius Malfoy',
        correctAnswer: 'answer1',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 8,
      },
      {
        questionTitle: 'What is the name of the game played on broomsticks in the Harry Potter series?',
        answer1: 'Quidditch',
        answer2: 'Broomstick Ball',
        answer3: "Wizard's Game",
        answer4: 'Flying Ball',
        correctAnswer: 'answer1',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 9,
      },
      {
        questionTitle: 'What is the name of the spell used to disarm an opponent?',
        answer1: 'Expelliarmus',
        answer2: 'Wingardium Leviosa',
        answer3: 'Alohomora',
        answer4: 'Avada Kedavra',
        correctAnswer: 'answer1',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 10,
      },
    ],
  },
  {
    Geography: [
      {
        questionTitle: 'Which of the following countries has the longest coastline?',
        answer1: 'Canada',
        answer2: 'Russia',
        answer3: 'Australia',
        answer4: 'Brazil',
        correctAnswer: 'answer1',
        questionType: 'quiz',
        questionTime: 15,
        questionPoints: 100,
        questionId: 1,
      },
      {
        questionTitle: 'True or False: The Great Barrier Reef is the largest coral reef system in the world.',
        answer1: 'True',
        answer2: 'False',
        correctAnswer: 'answer1',
        questionType: 'trueorfalse',
        questionTime: 10,
        questionPoints: 50,
        questionId: 2,
      },
      {
        questionTitle: 'Which of the following is NOT one of the Seven Wonders of the Ancient World?',
        answer1: 'The Great Wall of China',
        answer2: 'The Colossus of Rhodes',
        answer3: 'The Hanging Gardens of Babylon',
        answer4: 'The Lighthouse of Alexandria',
        correctAnswer: 'answer1',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 150,
        questionId: 3,
      },
      {
        questionTitle: 'True or False: Mount Everest is the tallest mountain in the world.',
        answer1: 'False',
        answer2: 'True',
        correctAnswer: 'answer1',
        questionType: 'trueorfalse',
        questionTime: 10,
        questionPoints: 50,
        questionId: 4,
      },
      {
        questionTitle: 'Which of the following countries is NOT in Europe?',
        answer1: 'Iceland',
        answer2: 'Norway',
        answer3: 'Switzerland',
        answer4: 'Argentina',
        correctAnswer: 'answer4',
        questionType: 'quiz',
        questionTime: 15,
        questionPoints: 100,
        questionId: 5,
      },
    ],
  },
  {
    History: [
      {
        questionTitle: 'True or False: The first successful airplane flight was by the Wright brothers.',
        answer1: 'True',
        answer2: 'False',
        correctAnswer: 'answer1',
        questionType: 'trueorfalse',
        questionTime: 10,
        questionPoints: 50,
        questionId: 6,
      },
      {
        questionTitle: 'Which of the following ancient civilizations is known for creating the first written language?',
        answer1: 'Egypt',
        answer2: 'Maya',
        answer3: 'Sumerian',
        answer4: 'Inca',
        correctAnswer: 'answer3',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 150,
        questionId: 7,
      },
      {
        questionTitle: 'True or False: Christopher Columbus discovered America.',
        answer1: 'False',
        answer2: 'True',
        correctAnswer: 'answer1',
        questionType: 'trueorfalse',
        questionTime: 10,
        questionPoints: 50,
        questionId: 8,
      },
      {
        questionTitle: 'In what year did World War II end?',
        answer1: '1945',
        answer2: '1955',
        answer3: '1935',
        answer4: '1925',
        correctAnswer: 'answer1',
        questionType: 'quiz',
        questionTime: 15,
        questionPoints: 100,
        questionId: 9,
      },
      {
        questionTitle: 'True or False: Julius Caesar was the first emperor of Rome.',
        answer1: 'False',
        answer2: 'True',
        correctAnswer: 'answer1',
        questionType: 'trueorfalse',
        questionTime: 10,
        questionPoints: 50,
        questionId: 10,
      },
    ],
  },
  {
    Technology: [
      {
        questionTitle: 'Bill Gates is the founder of which company?',
        answer1: 'Apple',
        answer2: 'Microsoft',
        answer3: 'Amazon',
        answer4: 'Tesla',
        correctAnswer: 'answer2',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 6,
      },
      {
        questionTitle: 'The first iPhone was released in what year?',
        answer1: '2004',
        answer2: '2005',
        answer3: '2006',
        answer4: '2007',
        correctAnswer: 'answer4',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 7,
      },
      {
        questionTitle: "The programming language 'Python' was named after which animal?",
        answer1: 'Lion',
        answer2: 'Python',
        answer3: 'Eagle',
        answer4: 'Giraffe',
        correctAnswer: 'answer2',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 8,
      },
      {
        questionTitle: 'What does HTML stand for?',
        answer1: 'Hyper Transfer Markup Language',
        answer2: 'Hyper Text Markup Language',
        answer3: 'Happy Text Markup Language',
        answer4: 'Hyper Transfered Markup Language',
        correctAnswer: 'answer2',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 9,
      },
      {
        questionTitle: 'True or False: A kilobyte is equal to 1000 bytes.',
        answer1: 'False',
        answer2: 'True',
        correctAnswer: 'answer1',
        questionType: 'trueorfalse',
        questionTime: 10,
        questionPoints: 200,
        questionId: 10,
      },
    ],
  },
  {
    'random topic': [
      {
        questionTitle: 'What is the capital of France?',
        answer1: 'London',
        answer2: 'Paris',
        answer3: 'Rome',
        answer4: 'Madrid',
        correctAnswer: 'answer2',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 1,
      },
      {
        questionTitle: 'Is the Great Barrier Reef located in Australia?',
        answer1: 'True',
        answer2: 'False',
        correctAnswer: 'answer1',
        questionType: 'trueorfalse',
        questionTime: 10,
        questionPoints: 200,
        questionId: 2,
      },
      {
        questionTitle: 'What is the currency of Japan?',
        answer1: 'Euro',
        answer2: 'Dollar',
        answer3: 'Yen',
        answer4: 'Pound',
        correctAnswer: 'answer3',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 3,
      },
      {
        questionTitle: 'Is the Earth flat?',
        answer1: 'True',
        answer2: 'False',
        correctAnswer: 'answer2',
        questionType: 'trueorfalse',
        questionTime: 10,
        questionPoints: 200,
        questionId: 4,
      },
      {
        questionTitle: 'What is the highest mountain in the world?',
        answer1: 'Mt. Kilimanjaro',
        answer2: 'Mt. Everest',
        answer3: 'Mt. Fuji',
        answer4: 'Mt. Denali',
        correctAnswer: 'answer2',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 5,
      },
      {
        questionTitle: 'Is the moon a planet?',
        answer1: 'True',
        answer2: 'False',
        correctAnswer: 'answer2',
        questionType: 'trueorfalse',
        questionTime: 10,
        questionPoints: 200,
        questionId: 6,
      },
      {
        questionTitle: 'What is the largest continent in the world?',
        answer1: 'North America',
        answer2: 'South America',
        answer3: 'Africa',
        answer4: 'Asia',
        correctAnswer: 'answer4',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 7,
      },
    ],
  },
  {
    Geography: [
      {
        questionTitle: 'What is the capital of France?',
        answer1: 'Berlin',
        answer2: 'London',
        answer3: 'Paris',
        answer4: 'Madrid',
        correctAnswer: 'answer3',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 1,
      },
      {
        questionTitle: 'Which country is both in Europe and Asia?',
        answer1: 'India',
        answer2: 'China',
        answer3: 'Russia',
        answer4: 'Australia',
        correctAnswer: 'answer3',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 2,
      },
      {
        questionTitle: 'Which of the following is the largest country in the world?',
        answer1: 'Canada',
        answer2: 'USA',
        answer3: 'China',
        answer4: 'Russia',
        correctAnswer: 'answer4',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 3,
      },
      {
        questionTitle: 'The Amazon River is located in which continent?',
        answer1: 'Africa',
        answer2: 'South America',
        answer3: 'North America',
        answer4: 'Europe',
        correctAnswer: 'answer2',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 4,
      },
      {
        questionTitle: 'The Great Barrier Reef is located in which country?',
        answer1: 'USA',
        answer2: 'Australia',
        answer3: 'Canada',
        answer4: 'Mexico',
        correctAnswer: 'answer2',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 5,
      },
      {
        questionTitle: 'The Nile River is the longest river in the world.',
        answer1: 'True',
        answer2: 'False',
        correctAnswer: 'answer2',
        questionTime: 10,
        questionType: 'trueorfalse',
        questionPoints: 200,
        questionId: 6,
      },
      {
        questionTitle: 'Mount Everest is located in which continent?',
        answer1: 'Asia',
        answer2: 'North America',
        answer3: 'Europe',
        answer4: 'Africa',
        correctAnswer: 'answer1',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 7,
      },
    ],
  },
  {
    History: [
      {
        questionTitle: 'Which country was ruled by the Ottoman Empire?',
        answer1: 'Spain',
        answer2: 'Turkey',
        answer3: 'Greece',
        answer4: 'Germany',
        correctAnswer: 'answer2',
        questionType: 'quiz',
        questionTime: 15,
        questionPoints: 100,
        questionId: 1,
      },
      {
        questionTitle: 'The Magna Carta was signed in which year?',
        answer1: '1215',
        answer2: '1415',
        answer3: '1615',
        answer4: '1815',
        correctAnswer: 'answer1',
        questionType: 'quiz',
        questionTime: 10,
        questionPoints: 80,
        questionId: 2,
      },
      {
        questionTitle: 'The American Civil War was fought from 1861 to 1865.',
        answer1: 'True',
        answer2: 'False',
        correctAnswer: 'answer1',
        questionType: 'trueorfalse',
        questionTime: 5,
        questionPoints: 50,
        questionId: 3,
      },
      {
        questionTitle: 'Who was the first President of the United States?',
        answer1: 'Abraham Lincoln',
        answer2: 'George Washington',
        answer3: 'Thomas Jefferson',
        answer4: 'John Adams',
        correctAnswer: 'answer2',
        questionType: 'quiz',
        questionTime: 12,
        questionPoints: 90,
        questionId: 4,
      },
      {
        questionTitle: 'The French Revolution began in which year?',
        answer1: '1789',
        answer2: '1889',
        answer3: '1689',
        answer4: '1589',
        correctAnswer: 'answer1',
        questionType: 'quiz',
        questionTime: 8,
        questionPoints: 70,
        questionId: 5,
      },
      {
        questionTitle: 'The Holocaust took place during which war?',
        answer1: 'World War I',
        answer2: 'World War II',
        answer3: 'Cold War',
        answer4: 'Vietnam War',
        correctAnswer: 'answer2',
        questionType: 'quiz',
        questionTime: 14,
        questionPoints: 120,
        questionId: 6,
      },
      {
        questionTitle: 'The Berlin Wall fell in which year?',
        answer1: '1989',
        answer2: '1979',
        answer3: '1969',
        answer4: '1959',
        correctAnswer: 'answer1',
        questionType: 'quiz',
        questionTime: 10,
        questionPoints: 80,
        questionId: 7,
      },
    ],
  },
  {
    'World Geography': [
      {
        questionTitle: 'What is the capital city of Australia?',
        answer1: 'Sydney',
        answer2: 'Melbourne',
        answer3: 'Brisbane',
        answer4: 'Canberra',
        correctAnswer: 'answer4',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 1,
      },
      {
        questionTitle: 'The longest river in the world is the Nile River.',
        answer1: 'True',
        answer2: 'False',
        correctAnswer: 'answer1',
        questionType: 'trueorfalse',
        questionTime: 10,
        questionPoints: 200,
        questionId: 2,
      },
      {
        questionTitle: 'Which country is both an island and a continent?',
        answer1: 'New Zealand',
        answer2: 'Australia',
        answer3: 'Indonesia',
        answer4: 'Madagascar',
        correctAnswer: 'answer2',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 3,
      },
      {
        questionTitle: 'The Great Barrier Reef is located in which country?',
        answer1: 'Mexico',
        answer2: 'Brazil',
        answer3: 'Australia',
        answer4: 'South Africa',
        correctAnswer: 'answer3',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 4,
      },
      {
        questionTitle: 'Mount Everest is the highest mountain in the world.',
        answer1: 'True',
        answer2: 'False',
        correctAnswer: 'answer1',
        questionType: 'trueorfalse',
        questionTime: 10,
        questionPoints: 200,
        questionId: 5,
      },
      {
        questionTitle: 'Which continent is the largest in terms of land area?',
        answer1: 'Africa',
        answer2: 'Asia',
        answer3: 'North America',
        answer4: 'Antarctica',
        correctAnswer: 'answer2',
        questionType: 'quiz',
        questionTime: 20,
        questionPoints: 100,
        questionId: 6,
      },
    ],
  },
];

export default quizzes;
